[{"fields": {"parsed_traceback": "{\"frames\":[{\"funcname\":\"get_response\",\"filepath\":\"python2.7/site-packages/django/core/handlers/base.py\",\"lineno\":\"112\",\"source_line\":\"response = wrapped_callback(request, *callback_args, **callback_kwargs)\"},{\"funcname\":\"inner\",\"filepath\":\"python2.7/site-packages/django/db/transaction.py\",\"lineno\":\"371\",\"source_line\":\"return func(*args, **kwargs)\"},{\"funcname\":\"wrapper\",\"filepath\":\"python2.7/site-packages/django/contrib/admin/options.py\",\"lineno\":\"465\",\"source_line\":\"return self.admin_site.admin_view(view)(*args, **kwargs)\"},{\"funcname\":\"_wrapped_view\",\"filepath\":\"python2.7/site-packages/django/utils/decorators.py\",\"lineno\":\"99\",\"source_line\":\"response = view_func(request, *args, **kwargs)\"},{\"funcname\":\"_wrapped_view_func\",\"filepath\":\"python2.7/site-packages/django/views/decorators/cache.py\",\"lineno\":\"52\",\"source_line\":\"response = view_func(request, *args, **kwargs)\"},{\"funcname\":\"inner\",\"filepath\":\"python2.7/site-packages/django/contrib/admin/sites.py\",\"lineno\":\"198\",\"source_line\":\"return view(request, *args, **kwargs)\"},{\"funcname\":\"_wrapper\",\"filepath\":\"python2.7/site-packages/django/utils/decorators.py\",\"lineno\":\"29\",\"source_line\":\"return bound_func(*args, **kwargs)\"},{\"funcname\":\"_wrapped_view\",\"filepath\":\"python2.7/site-packages/django/utils/decorators.py\",\"lineno\":\"99\",\"source_line\":\"response = view_func(request, *args, **kwargs)\"},{\"funcname\":\"bound_func\",\"filepath\":\"python2.7/site-packages/django/utils/decorators.py\",\"lineno\":\"25\",\"source_line\":\"return func(self, *args2, **kwargs2)\"},{\"funcname\":\"inner\",\"filepath\":\"python2.7/site-packages/django/db/transaction.py\",\"lineno\":\"371\",\"source_line\":\"return func(*args, **kwargs)\"},{\"funcname\":\"change_view\",\"filepath\":\"python2.7/site-packages/django/contrib/admin/options.py\",\"lineno\":\"1264\",\"source_line\":\"self.save_related(request, form, formsets, True)\"},{\"funcname\":\"save_related\",\"filepath\":\"python2.7/site-packages/django/contrib/admin/options.py\",\"lineno\":\"917\",\"source_line\":\"self.save_formset(request, form, formset, change=change)\"},{\"funcname\":\"save_formset\",\"filepath\":\"python2.7/site-packages/django/contrib/admin/options.py\",\"lineno\":\"905\",\"source_line\":\"formset.save()\"},{\"funcname\":\"save\",\"filepath\":\"python2.7/site-packages/django/forms/models.py\",\"lineno\":\"618\",\"source_line\":\"return self.save_existing_objects(commit) + self.save_new_objects(commit)\"},{\"funcname\":\"save_new_objects\",\"filepath\":\"python2.7/site-packages/django/forms/models.py\",\"lineno\":\"747\",\"source_line\":\"self.new_objects.append(self.save_new(form, commit=commit))\"},{\"funcname\":\"save_new\",\"filepath\":\"python2.7/site-packages/django/forms/models.py\",\"lineno\":\"877\",\"source_line\":\"obj.save()\"},{\"funcname\":\"save\",\"filepath\":\"python2.7/site-packages/django/db/models/base.py\",\"lineno\":\"545\",\"source_line\":\"force_update=force_update, update_fields=update_fields)\"},{\"funcname\":\"save_base\",\"filepath\":\"python2.7/site-packages/django/db/models/base.py\",\"lineno\":\"573\",\"source_line\":\"updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)\"},{\"funcname\":\"_save_table\",\"filepath\":\"python2.7/site-packages/django/db/models/base.py\",\"lineno\":\"654\",\"source_line\":\"result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)\"},{\"funcname\":\"_do_insert\",\"filepath\":\"python2.7/site-packages/django/db/models/base.py\",\"lineno\":\"687\",\"source_line\":\"using=using, raw=raw)\"},{\"funcname\":\"_insert\",\"filepath\":\"python2.7/site-packages/django/db/models/manager.py\",\"lineno\":\"232\",\"source_line\":\"return insert_query(self.model, objs, fields, **kwargs)\"},{\"funcname\":\"insert_query\",\"filepath\":\"python2.7/site-packages/django/db/models/query.py\",\"lineno\":\"1514\",\"source_line\":\"return query.get_compiler(using=using).execute_sql(return_id)\"},{\"funcname\":\"execute_sql\",\"filepath\":\"python2.7/site-packages/django/db/models/sql/compiler.py\",\"lineno\":\"903\",\"source_line\":\"cursor.execute(sql, params)\"},{\"funcname\":\"execute\",\"filepath\":\"python2.7/site-packages/django/db/backends/util.py\",\"lineno\":\"53\",\"source_line\":\"return self.cursor.execute(sql, params)\"},{\"funcname\":\"__exit__\",\"filepath\":\"python2.7/site-packages/django/db/utils.py\",\"lineno\":\"99\",\"source_line\":\"six.reraise(dj_exc_type, dj_exc_value, traceback)\"},{\"funcname\":\"execute\",\"filepath\":\"python2.7/site-packages/django/db/backends/util.py\",\"lineno\":\"53\",\"source_line\":\"return self.cursor.execute(sql, params)\"}],\"exc_type\":\"DataError\",\"exc_msg\":\"value too long for type character varying(100)\"}", "how_to_reproduce": "on models.py\r\n\r\n```\r\nclass ModelWithImage(models.Model):\r\n    image = models.ImageField()\r\n```\r\n\r\nwith `python manage.py shell`, run\r\n\r\n```\r\nfrom example.models import ModelWithImage\r\nx = ModelWithImage(image='a' * 300)\r\nx.save()\r\n```\r\n", "error_message": "value too long for type character varying(100)", "traceback": "Traceback (most recent call last):\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/core/handlers/base.py\", line 112, in get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/db/transaction.py\", line 371, in inner\n    return func(*args, **kwargs)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py\", line 465, in wrapper\n    return self.admin_site.admin_view(view)(*args, **kwargs)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/utils/decorators.py\", line 99, in _wrapped_view\n    response = view_func(request, *args, **kwargs)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/views/decorators/cache.py\", line 52, in _wrapped_view_func\n    response = view_func(request, *args, **kwargs)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py\", line 198, in inner\n    return view(request, *args, **kwargs)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/utils/decorators.py\", line 29, in _wrapper\n    return bound_func(*args, **kwargs)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/utils/decorators.py\", line 99, in _wrapped_view\n    response = view_func(request, *args, **kwargs)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/utils/decorators.py\", line 25, in bound_func\n    return func(self, *args2, **kwargs2)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/db/transaction.py\", line 371, in inner\n    return func(*args, **kwargs)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py\", line 1264, in change_view\n    self.save_related(request, form, formsets, True)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py\", line 917, in save_related\n    self.save_formset(request, form, formset, change=change)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py\", line 905, in save_formset\n    formset.save()\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/forms/models.py\", line 618, in save\n    return self.save_existing_objects(commit) + self.save_new_objects(commit)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/forms/models.py\", line 747, in save_new_objects\n    self.new_objects.append(self.save_new(form, commit=commit))\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/forms/models.py\", line 877, in save_new\n    obj.save()\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/db/models/base.py\", line 545, in save\n    force_update=force_update, update_fields=update_fields)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/db/models/base.py\", line 573, in save_base\n    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/db/models/base.py\", line 654, in _save_table\n    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/db/models/base.py\", line 687, in _do_insert\n    using=using, raw=raw)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/db/models/manager.py\", line 232, in _insert\n    return insert_query(self.model, objs, fields, **kwargs)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/db/models/query.py\", line 1514, in insert_query\n    return query.get_compiler(using=using).execute_sql(return_id)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py\", line 903, in execute_sql\n    cursor.execute(sql, params)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/db/backends/util.py\", line 53, in execute\n    return self.cursor.execute(sql, params)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/db/utils.py\", line 99, in __exit__\n    six.reraise(dj_exc_type, dj_exc_value, traceback)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/db/backends/util.py\", line 53, in execute\n    return self.cursor.execute(sql, params)\nDataError: value too long for type character varying(100)", "sanitized_traceback": "Traceback (most recent call last):\n  File \"python2.7/site-packages/django/core/handlers/base.py\", line 112, in get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"python2.7/site-packages/django/db/transaction.py\", line 371, in inner\n    return func(*args, **kwargs)\n  File \"python2.7/site-packages/django/contrib/admin/options.py\", line 465, in wrapper\n    return self.admin_site.admin_view(view)(*args, **kwargs)\n  File \"python2.7/site-packages/django/utils/decorators.py\", line 99, in _wrapped_view\n    response = view_func(request, *args, **kwargs)\n  File \"python2.7/site-packages/django/views/decorators/cache.py\", line 52, in _wrapped_view_func\n    response = view_func(request, *args, **kwargs)\n  File \"python2.7/site-packages/django/contrib/admin/sites.py\", line 198, in inner\n    return view(request, *args, **kwargs)\n  File \"python2.7/site-packages/django/utils/decorators.py\", line 29, in _wrapper\n    return bound_func(*args, **kwargs)\n  File \"python2.7/site-packages/django/utils/decorators.py\", line 99, in _wrapped_view\n    response = view_func(request, *args, **kwargs)\n  File \"python2.7/site-packages/django/utils/decorators.py\", line 25, in bound_func\n    return func(self, *args2, **kwargs2)\n  File \"python2.7/site-packages/django/db/transaction.py\", line 371, in inner\n    return func(*args, **kwargs)\n  File \"python2.7/site-packages/django/contrib/admin/options.py\", line 1264, in change_view\n    self.save_related(request, form, formsets, True)\n  File \"python2.7/site-packages/django/contrib/admin/options.py\", line 917, in save_related\n    self.save_formset(request, form, formset, change=change)\n  File \"python2.7/site-packages/django/contrib/admin/options.py\", line 905, in save_formset\n    formset.save()\n  File \"python2.7/site-packages/django/forms/models.py\", line 618, in save\n    return self.save_existing_objects(commit) + self.save_new_objects(commit)\n  File \"python2.7/site-packages/django/forms/models.py\", line 747, in save_new_objects\n    self.new_objects.append(self.save_new(form, commit=commit))\n  File \"python2.7/site-packages/django/forms/models.py\", line 877, in save_new\n    obj.save()\n  File \"python2.7/site-packages/django/db/models/base.py\", line 545, in save\n    force_update=force_update, update_fields=update_fields)\n  File \"python2.7/site-packages/django/db/models/base.py\", line 573, in save_base\n    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)\n  File \"python2.7/site-packages/django/db/models/base.py\", line 654, in _save_table\n    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)\n  File \"python2.7/site-packages/django/db/models/base.py\", line 687, in _do_insert\n    using=using, raw=raw)\n  File \"python2.7/site-packages/django/db/models/manager.py\", line 232, in _insert\n    return insert_query(self.model, objs, fields, **kwargs)\n  File \"python2.7/site-packages/django/db/models/query.py\", line 1514, in insert_query\n    return query.get_compiler(using=using).execute_sql(return_id)\n  File \"python2.7/site-packages/django/db/models/sql/compiler.py\", line 903, in execute_sql\n    cursor.execute(sql, params)\n  File \"python2.7/site-packages/django/db/backends/util.py\", line 53, in execute\n    return self.cursor.execute(sql, params)\n  File \"python2.7/site-packages/django/db/utils.py\", line 99, in __exit__\n    six.reraise(dj_exc_type, dj_exc_value, traceback)\n  File \"python2.7/site-packages/django/db/backends/util.py\", line 53, in execute\n    return self.cursor.execute(sql, params)\nDataError: value too long for type character varying(100)", "modified": "2015-07-23T07:13:51.237Z", "created": "2015-06-18T19:45:45.926Z", "exception_type": "DataError", "raised_by_line": 53, "raised_by": "django/db/backends/util.py", "slug": "db-backends-util-dataerror", "django_version": "1.6", "is_published": true}, "model": "error_posts.errorpost", "pk": 3}, {"fields": {"parsed_traceback": "{\"frames\":[{\"funcname\":\"get_response\",\"filepath\":\"python2.7/site-packages/django/core/handlers/base.py\",\"lineno\":\"111\",\"source_line\":\"response = wrapped_callback(request, *callback_args, **callback_kwargs)\"},{\"funcname\":\"view\",\"filepath\":\"python2.7/site-packages/django/views/generic/base.py\",\"lineno\":\"69\",\"source_line\":\"return self.dispatch(request, *args, **kwargs)\"},{\"funcname\":\"dispatch\",\"filepath\":\"python2.7/site-packages/braces/views/_access.py\",\"lineno\":\"64\",\"source_line\":\"request, *args, **kwargs)\"},{\"funcname\":\"dispatch\",\"filepath\":\"python2.7/site-packages/django/views/generic/base.py\",\"lineno\":\"87\",\"source_line\":\"return handler(request, *args, **kwargs)\"},{\"funcname\":\"post\",\"filepath\":\"python2.7/site-packages/django/views/generic/edit.py\",\"lineno\":\"207\",\"source_line\":\"return super(BaseCreateView, self).post(request, *args, **kwargs)\"},{\"funcname\":\"post\",\"filepath\":\"python2.7/site-packages/django/views/generic/edit.py\",\"lineno\":\"173\",\"source_line\":\"return self.form_valid(form)\"},{\"funcname\":\"private_function\",\"filepath\":\"private.py\",\"lineno\":\"1\",\"source_line\":\"private_function()\"},{\"funcname\":\"save\",\"filepath\":\"python2.7/site-packages/django/db/models/base.py\",\"lineno\":\"589\",\"source_line\":\"force_update=force_update, update_fields=update_fields)\"},{\"funcname\":\"save_base\",\"filepath\":\"python2.7/site-packages/django/db/models/base.py\",\"lineno\":\"626\",\"source_line\":\"update_fields=update_fields, raw=raw, using=using)\"},{\"funcname\":\"send\",\"filepath\":\"python2.7/site-packages/django/dispatch/dispatcher.py\",\"lineno\":\"198\",\"source_line\":\"response = receiver(signal=self, sender=sender, **named)\"},{\"funcname\":\"private_function\",\"filepath\":\"private.py\",\"lineno\":\"1\",\"source_line\":\"private_function()\"},{\"funcname\":\"private_function\",\"filepath\":\"private.py\",\"lineno\":\"1\",\"source_line\":\"private_function()\"},{\"funcname\":\"private_function\",\"filepath\":\"private.py\",\"lineno\":\"1\",\"source_line\":\"private_function()\"},{\"funcname\":\"send_templated_mail\",\"filepath\":\"python2.7/site-packages/templated_email/__init__.py\",\"lineno\":\"74\",\"source_line\":\"headers=headers, **kwargs)\"},{\"funcname\":\"send\",\"filepath\":\"python2.7/site-packages/templated_email/backends/vanilla_django.py\",\"lineno\":\"184\",\"source_line\":\"e.send(fail_silently)\"},{\"funcname\":\"send\",\"filepath\":\"python2.7/site-packages/django/core/mail/message.py\",\"lineno\":\"286\",\"source_line\":\"return self.get_connection(fail_silently).send_messages([self])\"},{\"funcname\":\"send_messages\",\"filepath\":\"python2.7/site-packages/django/core/mail/backends/smtp.py\",\"lineno\":\"99\",\"source_line\":\"sent = self._send(message)\"},{\"funcname\":\"_send\",\"filepath\":\"python2.7/site-packages/django/core/mail/backends/smtp.py\",\"lineno\":\"112\",\"source_line\":\"for addr in email_message.recipients()]\"},{\"funcname\":\"sanitize_address\",\"filepath\":\"python2.7/site-packages/django/core/mail/message.py\",\"lineno\":\"105\",\"source_line\":\"nm, addr = addr\"}],\"exc_type\":\"ValueError\",\"exc_msg\":\"too many values to unpack\"}", "how_to_reproduce": "\tfrom django.core.mail import EmailMessage\r\n\t\r\n\te = EmailMessage(\r\n\t    subject='test',\r\n\t    body='test',\r\n\t    from_email='from@example.org',\r\n\t    to=[['test1@example.org', 'test2@example.org', 'test3@example.org']],\r\n\t)\r\n\te.send()", "error_message": "too many values to unpack", "traceback": "Traceback (most recent call last):\n  File \"/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py\", line 111, in get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py\", line 69, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"/app/.heroku/python/lib/python2.7/site-packages/braces/views/_access.py\", line 64, in dispatch\n    request, *args, **kwargs)\n  File \"/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py\", line 87, in dispatch\n    return handler(request, *args, **kwargs)\n  File \"/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/edit.py\", line 207, in post\n    return super(BaseCreateView, self).post(request, *args, **kwargs)\n  File \"/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/edit.py\", line 173, in post\n    return self.form_valid(form)\n  File \"/app/shipments/views.py\", line 62, in form_valid\n    self.object.save()\n  File \"/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py\", line 589, in save\n    force_update=force_update, update_fields=update_fields)\n  File \"/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py\", line 626, in save_base\n    update_fields=update_fields, raw=raw, using=using)\n  File \"/app/.heroku/python/lib/python2.7/site-packages/django/dispatch/dispatcher.py\", line 198, in send\n    response = receiver(signal=self, sender=sender, **named)\n  File \"/app/shipments/signal_receivers.py\", line 22, in send_new_shipment_email\n    emails.send_shipment_email_to_all_nvocc(instance)\n  File \"/app/shipments/emails.py\", line 30, in send_shipment_email_to_all_nvocc\n    context={})\n  File \"/app/core/mail_utils.py\", line 15, in send_templated_mail\n    return templated_email.send_templated_mail(*args, **kwargs)\n  File \"/app/.heroku/python/lib/python2.7/site-packages/templated_email/__init__.py\", line 74, in send_templated_mail\n    headers=headers, **kwargs)\n  File \"/app/.heroku/python/lib/python2.7/site-packages/templated_email/backends/vanilla_django.py\", line 184, in send\n    e.send(fail_silently)\n  File \"/app/.heroku/python/lib/python2.7/site-packages/django/core/mail/message.py\", line 286, in send\n    return self.get_connection(fail_silently).send_messages([self])\n  File \"/app/.heroku/python/lib/python2.7/site-packages/django/core/mail/backends/smtp.py\", line 99, in send_messages\n    sent = self._send(message)\n  File \"/app/.heroku/python/lib/python2.7/site-packages/django/core/mail/backends/smtp.py\", line 112, in _send\n    for addr in email_message.recipients()]\n  File \"/app/.heroku/python/lib/python2.7/site-packages/django/core/mail/message.py\", line 105, in sanitize_address\n    nm, addr = addr\nValueError: too many values to unpack", "sanitized_traceback": "Traceback (most recent call last):\n  File \"python2.7/site-packages/django/core/handlers/base.py\", line 111, in get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"python2.7/site-packages/django/views/generic/base.py\", line 69, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"python2.7/site-packages/braces/views/_access.py\", line 64, in dispatch\n    request, *args, **kwargs)\n  File \"python2.7/site-packages/django/views/generic/base.py\", line 87, in dispatch\n    return handler(request, *args, **kwargs)\n  File \"python2.7/site-packages/django/views/generic/edit.py\", line 207, in post\n    return super(BaseCreateView, self).post(request, *args, **kwargs)\n  File \"python2.7/site-packages/django/views/generic/edit.py\", line 173, in post\n    return self.form_valid(form)\n  File \"private.py\", line 1, in private_function\n    private_function()\n  File \"python2.7/site-packages/django/db/models/base.py\", line 589, in save\n    force_update=force_update, update_fields=update_fields)\n  File \"python2.7/site-packages/django/db/models/base.py\", line 626, in save_base\n    update_fields=update_fields, raw=raw, using=using)\n  File \"python2.7/site-packages/django/dispatch/dispatcher.py\", line 198, in send\n    response = receiver(signal=self, sender=sender, **named)\n  File \"private.py\", line 1, in private_function\n    private_function()\n  File \"private.py\", line 1, in private_function\n    private_function()\n  File \"private.py\", line 1, in private_function\n    private_function()\n  File \"python2.7/site-packages/templated_email/__init__.py\", line 74, in send_templated_mail\n    headers=headers, **kwargs)\n  File \"python2.7/site-packages/templated_email/backends/vanilla_django.py\", line 184, in send\n    e.send(fail_silently)\n  File \"python2.7/site-packages/django/core/mail/message.py\", line 286, in send\n    return self.get_connection(fail_silently).send_messages([self])\n  File \"python2.7/site-packages/django/core/mail/backends/smtp.py\", line 99, in send_messages\n    sent = self._send(message)\n  File \"python2.7/site-packages/django/core/mail/backends/smtp.py\", line 112, in _send\n    for addr in email_message.recipients()]\n  File \"python2.7/site-packages/django/core/mail/message.py\", line 105, in sanitize_address\n    nm, addr = addr\nValueError: too many values to unpack", "modified": "2015-07-23T07:13:51.239Z", "created": "2015-06-18T19:58:57.215Z", "exception_type": "ValueError", "raised_by_line": 105, "raised_by": "django/core/mail/message.py", "slug": "core-mail-message-valueerror", "django_version": "1.7", "is_published": true}, "model": "error_posts.errorpost", "pk": 4}, {"fields": {"parsed_traceback": "{\"frames\":[{\"funcname\":\"get_response\",\"filepath\":\"python2.7/site-packages/django/core/handlers/base.py\",\"lineno\":\"112\",\"source_line\":\"response = wrapped_callback(request, *callback_args, **callback_kwargs)\"},{\"funcname\":\"inner\",\"filepath\":\"python2.7/site-packages/django/db/transaction.py\",\"lineno\":\"371\",\"source_line\":\"return func(*args, **kwargs)\"},{\"funcname\":\"wrapper\",\"filepath\":\"python2.7/site-packages/django/contrib/admin/options.py\",\"lineno\":\"465\",\"source_line\":\"return self.admin_site.admin_view(view)(*args, **kwargs)\"},{\"funcname\":\"_wrapped_view\",\"filepath\":\"python2.7/site-packages/django/utils/decorators.py\",\"lineno\":\"99\",\"source_line\":\"response = view_func(request, *args, **kwargs)\"},{\"funcname\":\"_wrapped_view_func\",\"filepath\":\"python2.7/site-packages/django/views/decorators/cache.py\",\"lineno\":\"52\",\"source_line\":\"response = view_func(request, *args, **kwargs)\"},{\"funcname\":\"inner\",\"filepath\":\"python2.7/site-packages/django/contrib/admin/sites.py\",\"lineno\":\"198\",\"source_line\":\"return view(request, *args, **kwargs)\"},{\"funcname\":\"_wrapper\",\"filepath\":\"python2.7/site-packages/django/utils/decorators.py\",\"lineno\":\"29\",\"source_line\":\"return bound_func(*args, **kwargs)\"},{\"funcname\":\"_wrapped_view\",\"filepath\":\"python2.7/site-packages/django/utils/decorators.py\",\"lineno\":\"99\",\"source_line\":\"response = view_func(request, *args, **kwargs)\"},{\"funcname\":\"bound_func\",\"filepath\":\"python2.7/site-packages/django/utils/decorators.py\",\"lineno\":\"25\",\"source_line\":\"return func(self, *args2, **kwargs2)\"},{\"funcname\":\"inner\",\"filepath\":\"python2.7/site-packages/django/db/transaction.py\",\"lineno\":\"371\",\"source_line\":\"return func(*args, **kwargs)\"},{\"funcname\":\"change_view\",\"filepath\":\"python2.7/site-packages/django/contrib/admin/options.py\",\"lineno\":\"1264\",\"source_line\":\"self.save_related(request, form, formsets, True)\"},{\"funcname\":\"save_related\",\"filepath\":\"python2.7/site-packages/django/contrib/admin/options.py\",\"lineno\":\"917\",\"source_line\":\"self.save_formset(request, form, formset, change=change)\"},{\"funcname\":\"save_formset\",\"filepath\":\"python2.7/site-packages/django/contrib/admin/options.py\",\"lineno\":\"905\",\"source_line\":\"formset.save()\"},{\"funcname\":\"save\",\"filepath\":\"python2.7/site-packages/django/forms/models.py\",\"lineno\":\"618\",\"source_line\":\"return self.save_existing_objects(commit) + self.save_new_objects(commit)\"},{\"funcname\":\"save_new_objects\",\"filepath\":\"python2.7/site-packages/django/forms/models.py\",\"lineno\":\"747\",\"source_line\":\"self.new_objects.append(self.save_new(form, commit=commit))\"},{\"funcname\":\"save_new\",\"filepath\":\"python2.7/site-packages/django/forms/models.py\",\"lineno\":\"877\",\"source_line\":\"obj.save()\"},{\"funcname\":\"save\",\"filepath\":\"python2.7/site-packages/django/db/models/base.py\",\"lineno\":\"545\",\"source_line\":\"force_update=force_update, update_fields=update_fields)\"},{\"funcname\":\"save_base\",\"filepath\":\"python2.7/site-packages/django/db/models/base.py\",\"lineno\":\"573\",\"source_line\":\"updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)\"},{\"funcname\":\"_save_table\",\"filepath\":\"python2.7/site-packages/django/db/models/base.py\",\"lineno\":\"654\",\"source_line\":\"result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)\"},{\"funcname\":\"_do_insert\",\"filepath\":\"python2.7/site-packages/django/db/models/base.py\",\"lineno\":\"687\",\"source_line\":\"using=using, raw=raw)\"},{\"funcname\":\"_insert\",\"filepath\":\"python2.7/site-packages/django/db/models/manager.py\",\"lineno\":\"232\",\"source_line\":\"return insert_query(self.model, objs, fields, **kwargs)\"},{\"funcname\":\"insert_query\",\"filepath\":\"python2.7/site-packages/django/db/models/query.py\",\"lineno\":\"1514\",\"source_line\":\"return query.get_compiler(using=using).execute_sql(return_id)\"},{\"funcname\":\"execute_sql\",\"filepath\":\"python2.7/site-packages/django/db/models/sql/compiler.py\",\"lineno\":\"903\",\"source_line\":\"cursor.execute(sql, params)\"},{\"funcname\":\"execute\",\"filepath\":\"python2.7/site-packages/django/db/backends/util.py\",\"lineno\":\"53\",\"source_line\":\"return self.cursor.execute(sql, params)\"},{\"funcname\":\"__exit__\",\"filepath\":\"python2.7/site-packages/django/db/utils.py\",\"lineno\":\"99\",\"source_line\":\"six.reraise(dj_exc_type, dj_exc_value, traceback)\"},{\"funcname\":\"execute\",\"filepath\":\"python2.7/site-packages/django/db/backends/util.py\",\"lineno\":\"56\",\"source_line\":\"return self.cursor.execute(sql, params)\"}],\"exc_type\":\"DataError2\",\"exc_msg\":\"value too long for type character varying(100)\"}", "how_to_reproduce": "on models.py\r\n\r\n```\r\nclass ModelWithImage(models.Model):\r\n    image = models.ImageField()\r\n```\r\n\r\nwith `python manage.py shell`, run\r\n\r\n```\r\nfrom example.models import ModelWithImage\r\nx = ModelWithImage(image='a' * 300)\r\nx.save()\r\n```\r\n", "error_message": "value too long for type character varying(100)", "traceback": "Traceback (most recent call last):\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/core/handlers/base.py\", line 112, in get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/db/transaction.py\", line 371, in inner\n    return func(*args, **kwargs)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py\", line 465, in wrapper\n    return self.admin_site.admin_view(view)(*args, **kwargs)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/utils/decorators.py\", line 99, in _wrapped_view\n    response = view_func(request, *args, **kwargs)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/views/decorators/cache.py\", line 52, in _wrapped_view_func\n    response = view_func(request, *args, **kwargs)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py\", line 198, in inner\n    return view(request, *args, **kwargs)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/utils/decorators.py\", line 29, in _wrapper\n    return bound_func(*args, **kwargs)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/utils/decorators.py\", line 99, in _wrapped_view\n    response = view_func(request, *args, **kwargs)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/utils/decorators.py\", line 25, in bound_func\n    return func(self, *args2, **kwargs2)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/db/transaction.py\", line 371, in inner\n    return func(*args, **kwargs)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py\", line 1264, in change_view\n    self.save_related(request, form, formsets, True)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py\", line 917, in save_related\n    self.save_formset(request, form, formset, change=change)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py\", line 905, in save_formset\n    formset.save()\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/forms/models.py\", line 618, in save\n    return self.save_existing_objects(commit) + self.save_new_objects(commit)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/forms/models.py\", line 747, in save_new_objects\n    self.new_objects.append(self.save_new(form, commit=commit))\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/forms/models.py\", line 877, in save_new\n    obj.save()\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/db/models/base.py\", line 545, in save\n    force_update=force_update, update_fields=update_fields)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/db/models/base.py\", line 573, in save_base\n    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/db/models/base.py\", line 654, in _save_table\n    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/db/models/base.py\", line 687, in _do_insert\n    using=using, raw=raw)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/db/models/manager.py\", line 232, in _insert\n    return insert_query(self.model, objs, fields, **kwargs)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/db/models/query.py\", line 1514, in insert_query\n    return query.get_compiler(using=using).execute_sql(return_id)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py\", line 903, in execute_sql\n    cursor.execute(sql, params)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/db/backends/util.py\", line 53, in execute\n    return self.cursor.execute(sql, params)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/db/utils.py\", line 99, in __exit__\n    six.reraise(dj_exc_type, dj_exc_value, traceback)\n  File \"/apps/desviantes/env/local/lib/python2.7/site-packages/django/db/backends/util.py\", line 56, in execute\n    return self.cursor.execute(sql, params)\nDataError2: value too long for type character varying(100)", "sanitized_traceback": "Traceback (most recent call last):\n  File \"python2.7/site-packages/django/core/handlers/base.py\", line 112, in get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"python2.7/site-packages/django/db/transaction.py\", line 371, in inner\n    return func(*args, **kwargs)\n  File \"python2.7/site-packages/django/contrib/admin/options.py\", line 465, in wrapper\n    return self.admin_site.admin_view(view)(*args, **kwargs)\n  File \"python2.7/site-packages/django/utils/decorators.py\", line 99, in _wrapped_view\n    response = view_func(request, *args, **kwargs)\n  File \"python2.7/site-packages/django/views/decorators/cache.py\", line 52, in _wrapped_view_func\n    response = view_func(request, *args, **kwargs)\n  File \"python2.7/site-packages/django/contrib/admin/sites.py\", line 198, in inner\n    return view(request, *args, **kwargs)\n  File \"python2.7/site-packages/django/utils/decorators.py\", line 29, in _wrapper\n    return bound_func(*args, **kwargs)\n  File \"python2.7/site-packages/django/utils/decorators.py\", line 99, in _wrapped_view\n    response = view_func(request, *args, **kwargs)\n  File \"python2.7/site-packages/django/utils/decorators.py\", line 25, in bound_func\n    return func(self, *args2, **kwargs2)\n  File \"python2.7/site-packages/django/db/transaction.py\", line 371, in inner\n    return func(*args, **kwargs)\n  File \"python2.7/site-packages/django/contrib/admin/options.py\", line 1264, in change_view\n    self.save_related(request, form, formsets, True)\n  File \"python2.7/site-packages/django/contrib/admin/options.py\", line 917, in save_related\n    self.save_formset(request, form, formset, change=change)\n  File \"python2.7/site-packages/django/contrib/admin/options.py\", line 905, in save_formset\n    formset.save()\n  File \"python2.7/site-packages/django/forms/models.py\", line 618, in save\n    return self.save_existing_objects(commit) + self.save_new_objects(commit)\n  File \"python2.7/site-packages/django/forms/models.py\", line 747, in save_new_objects\n    self.new_objects.append(self.save_new(form, commit=commit))\n  File \"python2.7/site-packages/django/forms/models.py\", line 877, in save_new\n    obj.save()\n  File \"python2.7/site-packages/django/db/models/base.py\", line 545, in save\n    force_update=force_update, update_fields=update_fields)\n  File \"python2.7/site-packages/django/db/models/base.py\", line 573, in save_base\n    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)\n  File \"python2.7/site-packages/django/db/models/base.py\", line 654, in _save_table\n    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)\n  File \"python2.7/site-packages/django/db/models/base.py\", line 687, in _do_insert\n    using=using, raw=raw)\n  File \"python2.7/site-packages/django/db/models/manager.py\", line 232, in _insert\n    return insert_query(self.model, objs, fields, **kwargs)\n  File \"python2.7/site-packages/django/db/models/query.py\", line 1514, in insert_query\n    return query.get_compiler(using=using).execute_sql(return_id)\n  File \"python2.7/site-packages/django/db/models/sql/compiler.py\", line 903, in execute_sql\n    cursor.execute(sql, params)\n  File \"python2.7/site-packages/django/db/backends/util.py\", line 53, in execute\n    return self.cursor.execute(sql, params)\n  File \"python2.7/site-packages/django/db/utils.py\", line 99, in __exit__\n    six.reraise(dj_exc_type, dj_exc_value, traceback)\n  File \"python2.7/site-packages/django/db/backends/util.py\", line 56, in execute\n    return self.cursor.execute(sql, params)\nDataError2: value too long for type character varying(100)", "modified": "2015-07-23T07:13:51.241Z", "created": "2015-07-08T19:59:12.885Z", "exception_type": "DataError2", "raised_by_line": 56, "raised_by": "django/db/backends/util.py", "slug": "db-backends-util-dataerror2", "django_version": "1.6", "is_published": true}, "model": "error_posts.errorpost", "pk": 8}, {"fields": {"date": "2015-06-18T20:59:00.499Z", "message": "Some library or yourself is trying to insert a value in a field that has `max_length=100` without a form or without cleaning the form, so the error is happening at db level. The field in question is probably a `FileField` or `ImageField` since their default `max_length` is 100 [1], which might not be enough for large paths.\r\n\r\nThe easiest solution is to increase field `max_length` to a value that is enough for your use case (ex: 255).\r\n\r\n[1] [https://docs.djangoproject.com/en/1.6/ref/models/fields/#filefield](https://docs.djangoproject.com/en/1.6/ref/models/fields/#filefield \"https://docs.djangoproject.com/en/1.6/ref/models/fields/#filefield\")", "error": 3, "modified": "2015-06-18T20:59:00.499Z", "created": "2015-06-18T20:57:20.091Z"}, "model": "error_posts.answer", "pk": 2}, {"fields": {"date": "2015-06-18T21:08:24.183Z", "message": "`to` parameter of [`EmailMessage`](https://docs.djangoproject.com/en/1.7/topics/email/#the-emailmessage-class \"EmailMessage\") (or `send_mail`) should not be a list of lists, but only a list. **Change `to` to a list.**", "error": 4, "modified": "2015-06-18T21:08:24.183Z", "created": "2015-06-18T21:01:31.039Z"}, "model": "error_posts.answer", "pk": 3}]